src/scripts/experience/experience-canvas.js
src/scripts/experience/issues-mode.js
src/scripts/experience/topics-mode.js

Resizes the canvas when the viewport size changes. Adds a new signal for modes to register onResize callbacks, and updates the Topics view to reposition properly when a resize happens.

Bug 1118847: Resize app when window resolution changes.

---

CONTRIBUTING.md
package.json

Add all dependecies to package json for even simpler local install

---

src/app/lorax/services/data.js

Pull data from bedrock

---

README.md

- Add Map Data source to README
- Add notes from original agency README (https://github.com/chrisjames-work/lorax)

[bug 1134830] Update README

---

src/app/lorax/directives/modal-mobile-options.tpl.html

@ckprice @pmclanahan @alexgibson r?

Fix Bug 1147351, remove legend link from mobile menu

---

contribute.json

add contribute.json

---

src/app/lorax/directives/modal-issue.js
src/scripts/experience/experience.js

@ckprice as the bug says, when you close an issue, you should be returned to the previous state i.e. ecosystem, checklist or vitals

Bug1147341 fix nav flow from new issue

---

src/scripts/experience/experience.js

Fix Bug 1146404, only show background circle in ecosystem mode

---

src/app/lorax/directives/modal-issue.js
src/styles/infographics/accessible.less
src/styles/modules/modal-issue.less

Revert font-size,weight and color. Small issue modal close bug fix

---

src/scripts/experience/experience.js
src/scripts/experience/topic.js
src/scripts/experience/topics-mode.js

Fix Bug 114436, add vitals description text to canvas

---

src/index.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1154766
@schalkneethling r?

[fix bug 1154766] Update GA with production ID

---

src/index.html

https://bugzilla.mozilla.org/show_bug.cgi?id=1154427
@schalkneethling r?

[fix bug 1154427] Add survey snippet

---

src/styles/base/header.less
src/styles/modules/colophon.less
src/styles/modules/modal-issue.less
src/styles/variables.less

Fix Bug 1154743, styling tweaks to issue modal

---

src/app/lorax/models/infographic.js
src/data/base/main.json

@ckprice r?
0 = green
1 = yellow
2 = red

Fix Bug 1154768, update issue colors

---

src/app/lorax/directives/chart-intellectual-property.js
src/app/lorax/lorax-app.js
src/data/base/main.json
src/data/i18n/infographics.json
src/styles/base/header.less
src/styles/infographics/intellectual-property.less
src/styles/main.less
src/styles/modules/infographics.less
src/styles/modules/modal-issue.less

@ckprice r? Added some options on how we can display the line graph here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1133831#c4
and added Greg for feedback.

Bug1133831 create intellectual property infographic

---

src/data/base/country-data.json
src/data/base/main.json
src/data/i18n/infographics.json
src/styles/modules/colophon.less

Fix Bug 1133817, add new speed infographic

---

src/app/lorax/directives/chart-surveillance.js
src/styles/infographics/surveillance.less
src/styles/main.less
src/styles/modules/infographics.less

@ckprice r? Not sure of the numbering is in the correct order so, let me know if it needs changing.

Fix Bug 1133824, updates to surveillance infographic

---

src/app/lorax/directives/modal-email.js
src/app/lorax/directives/modal-email.tpl.html
src/data/i18n/main.json
src/styles/base/scaffolding.less

https://bugzilla.mozilla.org/show_bug.cgi?id=1113270

[fix bug 1113270] Connect to mailing list

---

src/app/lorax/directives/modal-issue.js
src/app/lorax/directives/modal-issue.tpl.html
src/styles/modules/modal-issue.less

Fix Bug 1154743, more modal issue styling tweaks

---

src/app/lorax/directives/chart-identity-control.js
src/app/lorax/services/utils.js
src/data/i18n/infographics.json
src/styles/infographics/intellectual-property.less

Bug1133082 develop bar chart style infographic

---

src/app/lorax/directives/chart-identity-control.js
src/app/lorax/directives/chart-platform-neutrality.js
src/app/lorax/services/utils.js
src/data/i18n/infographics.json

@ckprice r? The bottom labels needs some tweaking but, I am sizing the chart down smaller which looks better I believe. Also did it here for the digital identities one.

Fix Bug 1133825, convert platform neutral to bar chart

---

src/app/lorax/directives/chart-concentration-power.js
src/app/lorax/directives/chart-concentration-power.tpl.html
src/data/i18n/infographics.json

Fix Bug 1133825, convert concentration of power to bar chart

---

src/app/lorax/directives/chart-accessible.js
src/app/lorax/directives/chart-accessible.tpl.html
src/app/lorax/directives/chart-cloud-security.js
src/app/lorax/directives/chart-cloud-security.tpl.html
src/app/lorax/directives/chart-common-languages.js
src/app/lorax/directives/chart-concentration-power.js
src/app/lorax/directives/chart-cyber-bullying.js
src/app/lorax/directives/chart-data-portability.js
src/app/lorax/directives/chart-data-portability.tpl.html
src/app/lorax/directives/chart-data-tracking.js
src/app/lorax/directives/chart-data-tracking.tpl.html
src/app/lorax/directives/chart-identity-control.js
src/app/lorax/directives/chart-infrastructure.js
src/app/lorax/directives/chart-intellectual-property.js
src/app/lorax/directives/chart-lobbying.js
src/app/lorax/directives/chart-open-source.js
src/app/lorax/directives/chart-open-source.tpl.html
src/app/lorax/directives/chart-platform-neutrality.js
src/app/lorax/directives/chart-public-trust.js
src/app/lorax/directives/chart-surveillance.js
src/app/lorax/directives/chart-world-map.js
src/app/lorax/services/utils.js
src/data/i18n/infographics.json
src/styles/infographics/data-portability.less
src/styles/modules/infographics.less
src/styles/modules/modal-issue.less

Fix Bug 1156363, show source for infographic when set.

---

src/styles/base/header.less

Fix Bug 1157776, avoid blocking pointer events on top of viewport nodes

---

src/app/lorax/directives/chart-common-languages.js
src/app/lorax/directives/chart-concentration-power.js
src/app/lorax/directives/chart-identity-control.js
src/app/lorax/directives/chart-platform-neutrality.js
src/app/lorax/services/utils.js
src/styles/modules/chart.less

Fix Bug 1133082, fixes to bar, column and grouped charts

---

src/app/lorax/directives/chart-security.js
src/app/lorax/lorax-app.js
src/app/lorax/models/infographic.js
src/app/lorax/services/utils.js
src/data/base/main.json
src/data/i18n/infographics.json
src/styles/infographics/circle-chart.less
src/styles/main.less

Fix Bug 1158368, add correct infographic to security issue modal

---

src/data/base/country-data.json
src/data/base/main.json
src/data/i18n/infographics.json

Fix Bug 1158370, put world map back on data protection issue

---

src/data/i18n/infographics.json

Switch invert to true for data protection

---

src/data/i18n/infographics.json

This wants to be .06, per discussion with Greg today.

[no-bug] Update Online Dating value

---

src/app/lorax/directives/chart-accessible.tpl.html
src/app/lorax/directives/modal-issue.js
src/app/lorax/directives/modal-issue.tpl.html
src/app/lorax/services/utils.js

Fix Bug 115851, open external links in new tab

---

src/scripts/experience/topics-mode.js

Fix Bug 1160375, remove vitals description text

---

src/styles/infographics/surveillance.less
src/styles/modules/modal-issue.less

Fix Bug 1154743, more tweaks to modal issue copy

---

src/styles/infographics/circle-chart.less
src/styles/infographics/surveillance.less
src/styles/modules/infographics.less
src/styles/modules/modal-issue.less

Fix Bug 1154743, additional styling tweaks based on feedback from Greg

---

Gruntfile.js
package.json

Do not clean icons-min dir

---

src/styles/modules/infographics.less

@ckprice r? based on https://bugzilla.mozilla.org/show_bug.cgi?id=1154743#c38

Bump down font size of source to 1rem

---

src/data/i18n/infographics.json

Take 2 with percentages this time.
@schalkneethling r?

[no-bug] JSON updates with Greg

---

src/app/lorax/directives/chart-open-source.js
src/app/lorax/directives/chart-open-source.tpl.html
src/app/lorax/services/utils.js
src/data/i18n/infographics.json
src/styles/modules/chart.less

@ckprice r? The chart is not exactly as the design but, I believe this conveys the data very well. Let me know, thanks!

Fix Bug 1158375, update line graph for open source issue

---

src/app/lorax/directives/chart-surveillance.js
src/data/i18n/infographics.json

@schalkneethling banged my head against the wall to figure out  how to rotate bubbles back. In the end, just rotated JSON. r?

[fix bug 1133824] Remove numbers, adjust JSON to rotate back

---

src/app/lorax/directives/chart-data-tracking.js
src/app/lorax/services/utils.js
src/data/i18n/infographics.json

Fixes to the ad tracking issue x labels

---

src/app/lorax/directives/chart-open-source.js
src/app/lorax/directives/chart-open-source.tpl.html
src/app/lorax/services/utils.js
src/styles/modules/chart.less
src/styles/modules/infographics.less

Fix Bug 1162279, update open source infographic styling

---

src/app/lorax/directives/modal-about.js
src/app/lorax/services/utils.js

Fix Bug 1163812, open about modal on ecosystem, vitals and checklist views

---

src/app/lorax/directives/experience.tpl.html
src/app/lorax/directives/modal-about.tpl.html
src/app/lorax/directives/modal-issue.js
src/app/lorax/directives/modal-issue.tpl.html
src/scripts/experience/experience.js
src/styles/modules/modal-issue.less

Fix Bug 1146310, ensure issue modal is accessible
